"use client";

import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ChevronDown, ChevronUp, Eye, LoaderCircle, ShieldCheck, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { api } from "@/lib/api";
import type { ApiCase } from "@/types/case";

type ModeratedCase = ApiCase & { ownerId: { name: string; email: string } };
type Decision = { item: ModeratedCase; kind: "approve" | "reject" };
const filters = ["All", "Under review", "Approved", "Rejected", "Draft"] as const;

export default function AdminCases() {
  const client = useQueryClient();
  const [filter, setFilter] = useState<(typeof filters)[number]>("Under review");
  const [expanded, setExpanded] = useState<string | null>(null);
  const [decision, setDecision] = useState<Decision | null>(null);
  const [note, setNote] = useState("");
  const query = useQuery({ queryKey: ["admin-cases"], queryFn: () => api<ModeratedCase[]>("/api/v1/admin/cases") });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ["admin-cases"] }), client.invalidateQueries({ queryKey: ["admin-analytics"] })]); };
  const moderation = useMutation({
    mutationFn: ({ item, kind, note }: Decision & { note: string }) => api(`/api/v1/admin/cases/${item._id}/moderation`, { method: "PATCH", body: JSON.stringify({ decision: kind, note }) }),
    onSuccess: async () => { setDecision(null); setNote(""); await refresh(); },
  });
  const removal = useMutation({ mutationFn: (id: string) => api(`/api/v1/admin/cases/${id}`, { method: "DELETE" }), onSuccess: refresh });
  const items = useMemo(() => (query.data || []).filter(item => filter === "All" || item.status === filter), [filter, query.data]);
  const counts = useMemo(() => Object.fromEntries(filters.map(value => [value, value === "All" ? query.data?.length || 0 : query.data?.filter(item => item.status === value).length || 0])), [query.data]);

  function openDecision(item: ModeratedCase, kind: Decision["kind"]) { setDecision({ item, kind }); setNote(kind === "approve" ? "Approved for public discovery." : ""); }

  return <div className="shell py-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Administrator</p><h1 className="mt-2 text-3xl font-extrabold">Case moderation</h1><p className="mt-3 max-w-2xl text-slate-600">Review the complete public submission, including any owner-approved AI insight, before it reaches Explore.</p></div><Link href="/admin" className="btn btn-secondary">Admin overview</Link></div>
    <div className="mt-7 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" aria-label="Filter cases">{filters.map(value => <button key={value} onClick={() => setFilter(value)} className={`shrink-0 rounded-full px-3.5 py-2 text-xs font-bold transition ${filter === value ? "bg-slate-900 text-white" : "border border-slate-200 bg-white text-slate-600 hover:border-violet-300"}`}>{value} <span className={filter === value ? "text-slate-300" : "text-slate-400"}>{counts[value]}</span></button>)}</div>
    {query.isLoading && <div className="card mt-7 grid place-items-center p-12 text-sm text-slate-500"><LoaderCircle className="mb-3 animate-spin text-[#6956e8]"/>Loading submissions…</div>}
    {query.isError && <div className="card mt-7 p-8 text-center"><p className="font-bold text-rose-700">{query.error.message}</p><button onClick={() => query.refetch()} className="btn btn-secondary mt-4">Retry</button></div>}
    {!query.isLoading && !query.isError && items.length === 0 && <div className="card mt-7 p-10 text-center"><ShieldCheck className="mx-auto text-[#0f9f91]"/><h2 className="mt-3 font-bold">No {filter === "All" ? "cases" : filter.toLowerCase() + " cases"}</h2><p className="mt-2 text-sm text-slate-500">There is nothing in this moderation queue.</p></div>}
    <div className="mt-7 space-y-4">{items.map(item => {
      const isOpen = expanded === item._id;
      return <article className="card overflow-hidden" key={item._id}>
        <div className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-extrabold text-slate-900">{item.title}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wider ${item.status === "Approved" ? "bg-teal-50 text-[#0f776e]" : item.status === "Rejected" ? "bg-rose-50 text-rose-700" : item.status === "Under review" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{item.status}</span></div><p className="mt-1 text-sm text-slate-500">{item.ownerId?.name || "Unknown author"} · {item.ownerId?.email} · {item.category} · <span className="capitalize">{item.visibility}</span></p></div><div className="flex flex-wrap gap-2"><button onClick={() => setExpanded(isOpen ? null : item._id)} className="btn btn-secondary text-sm">{isOpen ? <ChevronUp size={15}/> : <ChevronDown size={15}/>} {isOpen ? "Close review" : "Review"}</button>{item.status === "Approved" && <Link className="btn btn-secondary text-sm" href={`/items/${item.slug}`}><Eye size={15}/> View public</Link>}<button disabled={removal.isPending} onClick={() => { if (window.confirm(`Permanently remove “${item.title}” and its documents?`)) removal.mutate(item._id); }} className="btn btn-secondary text-sm text-rose-700"><Trash2 size={15}/> Remove</button></div></div>
        {isOpen && <div className="border-t border-slate-200 bg-slate-50/60 p-5 sm:p-6"><div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-6"><section><h3 className="text-xs font-extrabold uppercase tracking-wider text-slate-500">Public summary</h3><p className="mt-2 font-semibold leading-7 text-slate-900">{item.shortDescription}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{item.fullDescription}</p></section><div className="grid gap-4 sm:grid-cols-2"><ReviewList title="Goals" values={item.goals}/><ReviewList title="Constraints" values={item.constraints}/></div>{item.publicInsight?.title && item.publicInsight?.summary ? <section className="rounded-xl border border-teal-200 bg-white p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-[#0f776e]">Proposed public AI insight</p><h3 className="mt-2 font-bold">{item.publicInsight.title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{item.publicInsight.summary}</p><p className="mt-3 text-xs text-slate-400">Selected and published by the case owner</p></section> : <p className="rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-500">This case does not publish an AI insight.</p>}</div><aside className="space-y-4"><div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-slate-500">Submission details</p><dl className="mt-4 grid gap-3 text-sm"><Row label="Priority" value={item.priority}/><Row label="Visibility" value={item.visibility}/><Row label="Submitted" value={new Date(item.updatedAt).toLocaleString()}/><Row label="Tags" value={item.tags.length ? item.tags.join(", ") : "None"}/></dl></div>{item.moderationNote && <div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-slate-500">Latest moderation note</p><p className="mt-2 text-sm leading-6 text-slate-600">{item.moderationNote}</p></div>}{item.visibility === "public" && <div className="grid grid-cols-2 gap-2"><button disabled={moderation.isPending} onClick={() => openDecision(item, "reject")} className="btn border border-rose-200 bg-white text-rose-700"><X size={16}/> Reject</button><button disabled={moderation.isPending} onClick={() => openDecision(item, "approve")} className="btn bg-[#0f9f91] text-white"><Check size={16}/> Approve</button></div>}</aside></div></div>}
      </article>;
    })}</div>
    {decision && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="card w-full max-w-lg p-6" role="dialog" aria-modal="true" aria-labelledby="moderation-title"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Moderation decision</p><h2 id="moderation-title" className="mt-2 text-xl font-extrabold">{decision.kind === "approve" ? "Approve" : "Reject"} “{decision.item.title}”?</h2></div><button onClick={() => setDecision(null)} aria-label="Close"><X size={19}/></button></div><label className="mt-5 grid gap-2 text-sm font-bold">{decision.kind === "approve" ? "Approval note" : "Reason for rejection"}<textarea autoFocus value={note} onChange={event => setNote(event.target.value)} rows={4} maxLength={500} placeholder={decision.kind === "reject" ? "Explain what the owner needs to change before resubmitting." : "Optional internal/publication note"} className="rounded-lg border border-slate-300 p-3 font-normal leading-6"/></label>{moderation.isError && <p role="alert" className="mt-3 text-sm text-rose-700">{moderation.error.message}</p>}<p className="mt-3 text-xs leading-5 text-slate-500">{decision.kind === "approve" ? "The case will immediately become visible in Explore and public search." : "The owner will see this feedback and can resubmit after making changes."}</p><div className="mt-6 flex justify-end gap-2"><button disabled={moderation.isPending} onClick={() => setDecision(null)} className="btn btn-secondary">Cancel</button><button disabled={moderation.isPending || (decision.kind === "reject" && note.trim().length < 5)} onClick={() => moderation.mutate({ ...decision, note: note.trim() })} className={`btn text-white disabled:opacity-50 ${decision.kind === "approve" ? "bg-[#0f9f91]" : "bg-rose-700"}`}>{moderation.isPending ? "Saving…" : decision.kind === "approve" ? "Approve case" : "Reject case"}</button></div></div></div>}
  </div>;
}

function ReviewList({ title, values }: { title: string; values: string[] }) { return <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold">{title}</h3>{values.length ? <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">{values.map(value => <li key={value}>• {value}</li>)}</ul> : <p className="mt-2 text-sm text-slate-500">None provided.</p>}</section>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="grid grid-cols-[82px_1fr] gap-2"><dt className="text-slate-400">{label}</dt><dd className="break-words font-semibold capitalize text-slate-700">{value}</dd></div>; }
